apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
        containers:
          - name: backend
            image: o4317/eks-node-fargate-app:2.0
            ports:
              - containerPort: 5000
      #     env:
      #       - name: MONGO_URI
      #         value: "<your-mongo-atlas-uri>"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mern
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
